---
- name: Configure NginX and CloudWatch Agent
  hosts: web
  become: yes
  tasks:
    - name: Install NginX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Download CloudWatch Agent package
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb

    - name: Install CloudWatch Agent
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
        state: present

    - name: Enable and Start CloudWatch Agent
      systemd:
        name: amazon-cloudwatch-agent
        enabled: yes
        state: started

    - name: Ensure CloudWatch Agent config directory exists
      file:
        path: /opt/aws/amazon-cloudwatch-agent/etc
        state: directory
        mode: '0755'

    - name: Copy CloudWatch configuration file
      copy:
        src: ./amazon-cloudwatch-agent.json
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

    - name: Fetch CloudWatch Agent configuration
      command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -s
